## Preprocessing

In [5]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [6]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application = application_df.drop(columns=['NAME', 'EIN'])
application.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [87]:
# Determine the number of unique values in each column.
print(application.nunique())

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
app_count = application['APPLICATION_TYPE'].value_counts()

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_count[app_count < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
class_count = application['CLASSIFICATION'].value_counts()
class_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C8210        1
C1248        1
C1283        1
C2500        1
C1820        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application['CLASSIFICATION'].value_counts() >1

C1000     True
C2000     True
C1200     True
C3000     True
C2100     True
         ...
C8210    False
C1248    False
C1283    False
C2500    False
C1820    False
Name: CLASSIFICATION, Length: 71, dtype: bool

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_count[class_count < 500].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
convert_df = pd.get_dummies(application_df)
convert_df

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC,NAME_100 BLACK MEN OF AMERICA,NAME_100 BLACK MEN OF MEMPHIS INC,NAME_100 BLACK MEN OF WEST GEORGIA INC,NAME_1150 WEBSTER STREET INC,NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,10531628,1,108590,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,10547893,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,10553066,1,6692,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,10556103,1,142590,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,996010315,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,996012607,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,996015768,1,5000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,996086871,1,36500179,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [13]:
# Split our preprocessed data into our features and target arrays
y = convert_df["IS_SUCCESSFUL"]
X = convert_df.drop(["IS_SUCCESSFUL"],axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 5
hidden_nodes_layer2 = 15

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 5)                 98070

 dense_1 (Dense)             (None, 15)                90

 dense_2 (Dense)             (None, 1)                 16

=================================================================
Total params: 98,176
Trainable params: 98,176
Non-trainable params: 0
_________________________________________________________________

In [16]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=200)

Epoch 1/200
804/804 [==============================] - 25s 23ms/step - loss: 0.5948 - accuracy: 0.7026
Epoch 2/200
804/804 [==============================] - 17s 21ms/step - loss: 0.3656 - accuracy: 0.8502
Epoch 3/200
804/804 [==============================] - 14s 17ms/step - loss: 0.2564 - accuracy: 0.9055
Epoch 4/200
804/804 [==============================] - 20s 25ms/step - loss: 0.2316 - accuracy: 0.9118
Epoch 5/200
804/804 [==============================] - 14s 17ms/step - loss: 0.2225 - accuracy: 0.9141
Epoch 6/200
804/804 [==============================] - 19s 23ms/step - loss: 0.2203 - accuracy: 0.9149
Epoch 7/200
804/804 [==============================] - 21s 26ms/step - loss: 0.2157 - accuracy: 0.9162
Epoch 8/200
804/804 [==============================] - 13s 16ms/step - loss: 0.2118 - accuracy: 0.9181
Epoch 9/200
804/804 [==============================] - 14s 17ms/step - loss: 0.2089 - accuracy: 0.9181
Epoch 10/200
804/804 [==============================] - 13s 16ms/step - loss: 0.2061 - accuracy: 0.9206
Epoch 11/200
804/804 [==============================] - 12s 15ms/step - loss: 0.2031 - accuracy: 0.9229
Epoch 12/200
804/804 [==============================] - 13s 16ms/step - loss: 0.2008 - accuracy: 0.9256
Epoch 13/200
804/804 [==============================] - 14s 17ms/step - loss: 0.1986 - accuracy: 0.9292
Epoch 14/200
804/804 [==============================] - 13s 17ms/step - loss: 0.1979 - accuracy: 0.9295
Epoch 15/200
804/804 [==============================] - 21s 26ms/step - loss: 0.1961 - accuracy: 0.9301
Epoch 16/200
804/804 [==============================] - 20s 25ms/step - loss: 0.1873 - accuracy: 0.9308
Epoch 17/200
804/804 [==============================] - 18s 23ms/step - loss: 0.1783 - accuracy: 0.9304
Epoch 18/200
804/804 [==============================] - 18s 23ms/step - loss: 0.1726 - accuracy: 0.9310
Epoch 19/200
804/804 [==============================] - 23s 29ms/step - loss: 0.1703 - accuracy: 0.9313
Epoch 20/200
804/804 [==============================] - 18s 23ms/step - loss: 0.1687 - accuracy: 0.9315
Epoch 21/200
804/804 [==============================] - 20s 25ms/step - loss: 0.1667 - accuracy: 0.9328
Epoch 22/200
804/804 [==============================] - 19s 24ms/step - loss: 0.1660 - accuracy: 0.9322
Epoch 23/200
804/804 [==============================] - 17s 21ms/step - loss: 0.1653 - accuracy: 0.9323
Epoch 24/200
804/804 [==============================] - 20s 25ms/step - loss: 0.1647 - accuracy: 0.9322
Epoch 25/200
804/804 [==============================] - 17s 21ms/step - loss: 0.1636 - accuracy: 0.9333
Epoch 26/200
804/804 [==============================] - 15s 19ms/step - loss: 0.1631 - accuracy: 0.9331
Epoch 27/200
804/804 [==============================] - 18s 22ms/step - loss: 0.1631 - accuracy: 0.9335
Epoch 28/200
804/804 [==============================] - 16s 20ms/step - loss: 0.1629 - accuracy: 0.9324
Epoch 29/200
804/804 [==============================] - 17s 21ms/step - loss: 0.1622 - accuracy: 0.9330
Epoch 30/200
804/804 [==============================] - 19s 24ms/step - loss: 0.1623 - accuracy: 0.9336
Epoch 31/200
804/804 [==============================] - 19s 24ms/step - loss: 0.1620 - accuracy: 0.9333
Epoch 32/200
804/804 [==============================] - 21s 26ms/step - loss: 0.1618 - accuracy: 0.9328
Epoch 33/200
804/804 [==============================] - 18s 23ms/step - loss: 0.1613 - accuracy: 0.9333
Epoch 34/200
804/804 [==============================] - 22s 27ms/step - loss: 0.1609 - accuracy: 0.9332
Epoch 35/200
804/804 [==============================] - 22s 28ms/step - loss: 0.1611 - accuracy: 0.9334
Epoch 36/200
804/804 [==============================] - 21s 26ms/step - loss: 0.1607 - accuracy: 0.9330
Epoch 37/200
804/804 [==============================] - 15s 19ms/step - loss: 0.1603 - accuracy: 0.9337
Epoch 38/200
804/804 [==============================] - 19s 23ms/step - loss: 0.1599 - accuracy: 0.9337
Epoch 39/200
804/804 [==============================] - 22s 28ms/step - loss: 0.1593 - accuracy: 0.9337
Epoch 40/200
804/804 [==============================] - 20s 25ms/step - loss: 0.1591 - accuracy: 0.9340
Epoch 41/200
804/804 [==============================] - 19s 24ms/step - loss: 0.1589 - accuracy: 0.9337
Epoch 42/200
804/804 [==============================] - 19s 23ms/step - loss: 0.1592 - accuracy: 0.9342
Epoch 43/200
804/804 [==============================] - 16s 19ms/step - loss: 0.1581 - accuracy: 0.9340
Epoch 44/200
804/804 [==============================] - 18s 22ms/step - loss: 0.1586 - accuracy: 0.9341
Epoch 45/200
804/804 [==============================] - 21s 26ms/step - loss: 0.1585 - accuracy: 0.9341
Epoch 46/200
804/804 [==============================] - 19s 23ms/step - loss: 0.1578 - accuracy: 0.9345
Epoch 47/200
804/804 [==============================] - 14s 18ms/step - loss: 0.1576 - accuracy: 0.9350
Epoch 48/200
804/804 [==============================] - 18s 22ms/step - loss: 0.1584 - accuracy: 0.9345
Epoch 49/200
804/804 [==============================] - 16s 20ms/step - loss: 0.1627 - accuracy: 0.9312
Epoch 50/200
804/804 [==============================] - 16s 20ms/step - loss: 0.1570 - accuracy: 0.9327
Epoch 51/200
804/804 [==============================] - 18s 22ms/step - loss: 0.1492 - accuracy: 0.9329
Epoch 52/200
804/804 [==============================] - 19s 23ms/step - loss: 0.1454 - accuracy: 0.9336
Epoch 53/200
804/804 [==============================] - 23s 28ms/step - loss: 0.1414 - accuracy: 0.9352
Epoch 54/200
804/804 [==============================] - 21s 26ms/step - loss: 0.1379 - accuracy: 0.9380
Epoch 55/200
804/804 [==============================] - 20s 25ms/step - loss: 0.1435 - accuracy: 0.9401
Epoch 56/200
804/804 [==============================] - 13s 16ms/step - loss: 0.1434 - accuracy: 0.9397
Epoch 57/200
804/804 [==============================] - 13s 17ms/step - loss: 0.1356 - accuracy: 0.9400
Epoch 58/200
804/804 [==============================] - 15s 18ms/step - loss: 0.1345 - accuracy: 0.9402
Epoch 59/200
804/804 [==============================] - 13s 16ms/step - loss: 0.1328 - accuracy: 0.9402
Epoch 60/200
804/804 [==============================] - 16s 20ms/step - loss: 0.1313 - accuracy: 0.9407
Epoch 61/200
804/804 [==============================] - 14s 18ms/step - loss: 0.1298 - accuracy: 0.9408
Epoch 62/200
804/804 [==============================] - 11s 14ms/step - loss: 0.1278 - accuracy: 0.9425
Epoch 63/200
804/804 [==============================] - 18s 22ms/step - loss: 0.1317 - accuracy: 0.9419
Epoch 64/200
804/804 [==============================] - 12s 15ms/step - loss: 0.1321 - accuracy: 0.9439
Epoch 65/200
804/804 [==============================] - 13s 16ms/step - loss: 0.1303 - accuracy: 0.9441
Epoch 66/200
804/804 [==============================] - 13s 16ms/step - loss: 0.1270 - accuracy: 0.9430
Epoch 67/200
804/804 [==============================] - 11s 13ms/step - loss: 0.1266 - accuracy: 0.9434
Epoch 68/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1260 - accuracy: 0.9444
Epoch 69/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1251 - accuracy: 0.9435
Epoch 70/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1230 - accuracy: 0.9464
Epoch 71/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1235 - accuracy: 0.9472
Epoch 72/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1236 - accuracy: 0.9463
Epoch 73/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1225 - accuracy: 0.9461
Epoch 74/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1200 - accuracy: 0.9490
Epoch 75/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1200 - accuracy: 0.9488
Epoch 76/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1172 - accuracy: 0.9511
Epoch 77/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1180 - accuracy: 0.9506
Epoch 78/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1161 - accuracy: 0.9521
Epoch 79/200

804/804 [==============================] - 10s 12ms/step - loss: 0.1149 - accuracy: 0.9535
Epoch 80/200
804/804 [==============================] - 9s 12ms/step - loss: 0.1154 - accuracy: 0.9534
Epoch 81/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1140 - accuracy: 0.9530
Epoch 82/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1137 - accuracy: 0.9540
Epoch 83/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1133 - accuracy: 0.9541
Epoch 84/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1124 - accuracy: 0.9542
Epoch 85/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1121 - accuracy: 0.9546
Epoch 86/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1127 - accuracy: 0.9533
Epoch 87/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1116 - accuracy: 0.9549
Epoch 88/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1118 - accuracy: 0.9543
Epoch 89/200
804/804 [==============================] - 6s 8ms/step - loss: 0.1108 - accuracy: 0.9545
Epoch 90/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1112 - accuracy: 0.9547
Epoch 91/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1110 - accuracy: 0.9543
Epoch 92/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1107 - accuracy: 0.9555
Epoch 93/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1096 - accuracy: 0.9551
Epoch 94/200
804/804 [==============================] - 6s 8ms/step - loss: 0.1112 - accuracy: 0.9550
Epoch 95/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1099 - accuracy: 0.9548
Epoch 96/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1091 - accuracy: 0.9554
Epoch 97/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1100 - accuracy: 0.9550
Epoch 98/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1096 - accuracy: 0.9547
Epoch 99/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1088 - accuracy: 0.9559
Epoch 100/200
804/804 [==============================] - 6s 8ms/step - loss: 0.1084 - accuracy: 0.9553
Epoch 101/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1077 - accuracy: 0.9558
Epoch 102/200
804/804 [==============================] - 6s 8ms/step - loss: 0.1078 - accuracy: 0.9558
Epoch 103/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1081 - accuracy: 0.9558
Epoch 104/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1085 - accuracy: 0.9558
Epoch 105/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1247 - accuracy: 0.9471
Epoch 106/200
804/804 [==============================] - 6s 8ms/step - loss: 0.1273 - accuracy: 0.9480
Epoch 107/200
804/804 [==============================] - 10s 13ms/step - loss: 0.1144 - accuracy: 0.9555
Epoch 108/200
804/804 [==============================] - 14s 17ms/step - loss: 0.1062 - accuracy: 0.9588
Epoch 109/200
804/804 [==============================] - 11s 14ms/step - loss: 0.1030 - accuracy: 0.9602
Epoch 110/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1019 - accuracy: 0.9595
Epoch 111/200
804/804 [==============================] - 10s 12ms/step - loss: 0.1003 - accuracy: 0.9596
Epoch 112/200
804/804 [==============================] - 10s 12ms/step - loss: 0.0991 - accuracy: 0.9605
Epoch 113/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0991 - accuracy: 0.9598
Epoch 114/200
804/804 [==============================] - 6s 8ms/step - loss: 0.0984 - accuracy: 0.9608
Epoch 115/200
804/804 [==============================] - 10s 12ms/step - loss: 0.0984 - accuracy: 0.9601
Epoch 116/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0982 - accuracy: 0.9599
Epoch 117/200
804/804 [==============================] - 10s 12ms/step - loss: 0.0973 - accuracy: 0.9602
Epoch 118/200
804/804 [==============================] - 6s 8ms/step - loss: 0.0977 - accuracy: 0.9603
Epoch 119/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0977 - accuracy: 0.9603
Epoch 120/200
804/804 [==============================] - 11s 14ms/step - loss: 0.0978 - accuracy: 0.9605
Epoch 121/200
804/804 [==============================] - 11s 14ms/step - loss: 0.0975 - accuracy: 0.9601
Epoch 122/200
804/804 [==============================] - 10s 12ms/step - loss: 0.0976 - accuracy: 0.9610
Epoch 123/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0970 - accuracy: 0.9610
Epoch 124/200
804/804 [==============================] - 7s 8ms/step - loss: 0.0968 - accuracy: 0.9606
Epoch 125/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0966 - accuracy: 0.9616
Epoch 126/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0966 - accuracy: 0.9605
Epoch 127/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0967 - accuracy: 0.9597
Epoch 128/200
804/804 [==============================] - 7s 8ms/step - loss: 0.0966 - accuracy: 0.9608
Epoch 129/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0961 - accuracy: 0.9607
Epoch 130/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0965 - accuracy: 0.9604
Epoch 131/200
804/804 [==============================] - 10s 12ms/step - loss: 0.0958 - accuracy: 0.9604
Epoch 132/200
804/804 [==============================] - 7s 8ms/step - loss: 0.0959 - accuracy: 0.9611
Epoch 133/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0963 - accuracy: 0.9602
Epoch 134/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0955 - accuracy: 0.9608
Epoch 135/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0969 - accuracy: 0.9601
Epoch 136/200
804/804 [==============================] - 6s 8ms/step - loss: 0.0965 - accuracy: 0.9602
Epoch 137/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0965 - accuracy: 0.9603
Epoch 138/200
804/804 [==============================] - 9s 11ms/step - loss: 0.0953 - accuracy: 0.9605
Epoch 139/200
804/804 [==============================] - 7s 9ms/step - loss: 0.0954 - accuracy: 0.9605
Epoch 140/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0957 - accuracy: 0.9609
Epoch 141/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0954 - accuracy: 0.9600
Epoch 142/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0952 - accuracy: 0.9608
Epoch 143/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0951 - accuracy: 0.9609
Epoch 144/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0956 - accuracy: 0.9607
Epoch 145/200
804/804 [==============================] - 7s 8ms/step - loss: 0.0950 - accuracy: 0.9610
Epoch 146/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0961 - accuracy: 0.9608
Epoch 147/200
804/804 [==============================] - 10s 12ms/step - loss: 0.0953 - accuracy: 0.9610
Epoch 148/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0950 - accuracy: 0.9613
Epoch 149/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0952 - accuracy: 0.9609
Epoch 150/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0958 - accuracy: 0.9605
Epoch 151/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0944 - accuracy: 0.9610
Epoch 152/200
804/804 [==============================] - 7s 8ms/step - loss: 0.0943 - accuracy: 0.9617
Epoch 153/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0952 - accuracy: 0.9610
Epoch 154/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0949 - accuracy: 0.9607
Epoch 155/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0944 - accuracy: 0.9616
Epoch 156/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0952 - accuracy: 0.9616
Epoch 157/200

804/804 [==============================] - 6s 8ms/step - loss: 0.0947 - accuracy: 0.9609
Epoch 158/200
804/804 [==============================] - 10s 12ms/step - loss: 0.0941 - accuracy: 0.9619
Epoch 159/200
804/804 [==============================] - 10s 12ms/step - loss: 0.0949 - accuracy: 0.9615
Epoch 160/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0942 - accuracy: 0.9609
Epoch 161/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0942 - accuracy: 0.9612
Epoch 162/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0941 - accuracy: 0.9615
Epoch 163/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0950 - accuracy: 0.9612
Epoch 164/200
804/804 [==============================] - 13s 16ms/step - loss: 0.0946 - accuracy: 0.9612
Epoch 165/200
804/804 [==============================] - 19s 24ms/step - loss: 0.0953 - accuracy: 0.9614
Epoch 166/200
804/804 [==============================] - 15s 19ms/step - loss: 0.0939 - accuracy: 0.9619
Epoch 167/200
804/804 [==============================] - 16s 20ms/step - loss: 0.0941 - accuracy: 0.9616
Epoch 168/200
804/804 [==============================] - 16s 20ms/step - loss: 0.0940 - accuracy: 0.9616
Epoch 169/200
804/804 [==============================] - 17s 21ms/step - loss: 0.0942 - accuracy: 0.9610
Epoch 170/200
804/804 [==============================] - 17s 21ms/step - loss: 0.0939 - accuracy: 0.9611
Epoch 171/200
804/804 [==============================] - 15s 18ms/step - loss: 0.0940 - accuracy: 0.9614
Epoch 172/200
804/804 [==============================] - 14s 17ms/step - loss: 0.0939 - accuracy: 0.9616
Epoch 173/200
804/804 [==============================] - 15s 19ms/step - loss: 0.0936 - accuracy: 0.9614
Epoch 174/200
804/804 [==============================] - 15s 19ms/step - loss: 0.0933 - accuracy: 0.9618
Epoch 175/200
804/804 [==============================] - 16s 20ms/step - loss: 0.0941 - accuracy: 0.9612
Epoch 176/200
804/804 [==============================] - 17s 21ms/step - loss: 0.0941 - accuracy: 0.9613
Epoch 177/200
804/804 [==============================] - 15s 19ms/step - loss: 0.0934 - accuracy: 0.9615
Epoch 178/200
804/804 [==============================] - 18s 22ms/step - loss: 0.0940 - accuracy: 0.9609
Epoch 179/200
804/804 [==============================] - 17s 21ms/step - loss: 0.0940 - accuracy: 0.9616
Epoch 180/200
804/804 [==============================] - 16s 20ms/step - loss: 0.0937 - accuracy: 0.9623
Epoch 181/200
804/804 [==============================] - 18s 22ms/step - loss: 0.0941 - accuracy: 0.9616
Epoch 182/200
804/804 [==============================] - 14s 17ms/step - loss: 0.0938 - accuracy: 0.9617
Epoch 183/200
804/804 [==============================] - 21s 26ms/step - loss: 0.0940 - accuracy: 0.9612
Epoch 184/200
804/804 [==============================] - 20s 25ms/step - loss: 0.0935 - accuracy: 0.9610
Epoch 185/200
804/804 [==============================] - 16s 20ms/step - loss: 0.0931 - accuracy: 0.9616
Epoch 186/200
804/804 [==============================] - 14s 18ms/step - loss: 0.0934 - accuracy: 0.9612
Epoch 187/200
804/804 [==============================] - 19s 23ms/step - loss: 0.0937 - accuracy: 0.9619
Epoch 188/200
804/804 [==============================] - 13s 16ms/step - loss: 0.0938 - accuracy: 0.9609
Epoch 189/200
804/804 [==============================] - 12s 14ms/step - loss: 0.0936 - accuracy: 0.9616
Epoch 190/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0930 - accuracy: 0.9621
Epoch 191/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0934 - accuracy: 0.9616
Epoch 192/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0928 - accuracy: 0.9615
Epoch 193/200
804/804 [==============================] - 10s 13ms/step - loss: 0.0931 - accuracy: 0.9616
Epoch 194/200
804/804 [==============================] - 7s 8ms/step - loss: 0.0939 - accuracy: 0.9613
Epoch 195/200
804/804 [==============================] - 10s 12ms/step - loss: 0.0932 - accuracy: 0.9627
Epoch 196/200
804/804 [==============================] - 11s 14ms/step - loss: 0.0937 - accuracy: 0.9615
Epoch 197/200
804/804 [==============================] - 11s 13ms/step - loss: 0.0928 - accuracy: 0.9618
Epoch 198/200
804/804 [==============================] - 7s 9ms/step - loss: 0.0957 - accuracy: 0.9611
Epoch 199/200
804/804 [==============================] - 11s 14ms/step - loss: 0.0934 - accuracy: 0.9623
Epoch 200/200
804/804 [==============================] - 17s 21ms/step - loss: 0.0934 - accuracy: 0.9620

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 2s - loss: 0.5192 - accuracy: 0.7623 - 2s/epoch - 6ms/step
Loss: 0.5192241072654724, Accuracy: 0.7623323798179626

In [19]:
# Export our model to HDF5 file
nn.save('Models/AlphabetSoupCharity.h5')